name: Export and Publish Rapid's Create & Miscellaneous ModPack

on:
  push:
    branches:
      - main

jobs:
  export-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract version from pack.toml
        id: extract_version
        run: |
          version=$(grep '^version' pack.toml | cut -d '"' -f2)
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Extracted version: $version"  # Debugging output

      - name: Check if release exists
        id: check_release
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: |
          echo "Checking release for version: $VERSION" # Debug output
          response=$(curl -s -H "Authorization: token $GITEA_TOKEN" "https://git.rapidfuge.xyz/api/v1/repos/RapidFuge/Create-Server-Modpack/releases/tags/v$VERSION")
          echo "API response: $response" # Debug output
          if [[ $(echo $response | jq -r '.message') == "The target couldn't be found." ]]; then
            echo "Release does not exist."
            echo "release_exists=false" >> $GITHUB_ENV
          else
            echo "Release exists."
            echo "release_exists=true" >> $GITHUB_ENV
          fi

      - name: Download packwiz binary
        if: env.release_exists == 'false'
        run: |
          # Download the packwiz binary directly from the provided URL
          curl -L -o packwiz https://github.com/walksanatora/HexxyTestPack/raw/main/packwiz/packwiz
          chmod +x packwiz
          sudo mv packwiz /usr/local/bin/packwiz

      - name: Export modpack to Modrinth
        if: env.release_exists == 'false'
        run: |
          packwiz modrinth export -o rapids-create-misc-modpack.mrpack

      - name: Create release and upload .mrpack file
        if: env.release_exists == 'false'
        uses: akkuman/gitea-release-action@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "Rapid's Create & Miscellaneous ModPack v${{ env.VERSION }}"
          token: ${{ secrets.GITEA_TOKEN }}
          files: |
            rapids-create-misc-modpack.mrpack

      # - name: Upload to Modrinth
      #   env:
      #     MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      #     VERSION: ${{ env.VERSION }}
      #   run: |
      #     echo "Uploading to Modrinth with version: $VERSION" # Debug output
      #     curl -X POST https://api.modrinth.com/v2/version \
      #     -H "Authorization: Bearer $MODRINTH_TOKEN" \
      #     -H "Content-Type: application/json" \
      #     -d '{
      #       "name": "Rapid'\''s Create & Miscellaneous ModPack - '"$VERSION"'",
      #       "version_number": "'"$VERSION"'",
      #       "changelog": "Automated release",
      #       "dependencies": [],
      #       "files": [
      #         {
      #           "url": "https://path-to-your-file/rapids-create-misc-modpack.mrpack",
      #           "filename": "rapids-create-misc-modpack.mrpack"
      #         }
      #       ]
      #     }'
