name: Release Mods

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release"
        required: true
        default: "1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          python -m pip install toml requests

      - name: Download mods
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: |
          mkdir -p mods/client mods/server
          python download_mods.py

      - name: Create ZIP files
        run: |
          zip -r client-mods.zip mods/client
          zip -r server-mods.zip mods/server

      - name: Set Tag Name
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "::set-output name=tag_name::${{ github.event.inputs.tag_name }}"
          else
            echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.set_tag.outputs.tag_name }}
          release_name: Release ${{ steps.set_tag.outputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (Client)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./client-mods.zip
          asset_name: client-mods.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (Server)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./server-mods.zip
          asset_name: server-mods.zip
          asset_content_type: application/zip

      - name: Upload Mod Summary
        uses: actions/upload-artifact@v3
        with:
          name: mod-summary
          path: mod_summary.txt

      - name: Set Release Description
        id: set_description
        run: |
          description=$(cat mod_summary.txt)
          echo "::set-output name=description::$description"

      - name: Update Release with Description
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/releases/{release_id}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          release_id: ${{ steps.create_release.outputs.id }}
          description: ${{ steps.set_description.outputs.description }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
